fixing monitoring

diff --git a/bin/apply b/bin/apply
--- a/bin/apply
+++ b/bin/apply
@@ -1,42 +1,54 @@
 #!/bin/sh -eu
 
-apply=${1:-deploy}
-
-export base=$(cd $(dirname "$0")/..; pwd)
-export tmp=$(mktemp)
-export host=host/$(hostname -s)
-export exit=0
-
-trap 'rm -rf "$tmp"' INT TERM EXIT HUP
+die() {
+	echo >&2 "error: $*"
+	exit 1
+}
 
 o() {
-	"$base/bin/do-$apply" "$@"
+	"$base/bin/do/$apply" "$@" "$arg"
 }
 
 module() {
-	local module=${1:?}
-	export dest=/etc/${module#module/}
+	local item=${1:?} arg=${2:-}
+	export etc=/etc/${item#module/}
 
-	echo >&2 ">>> $apply $module"
-	(cd "$base/$module"; . ./mod; :) || {
-		echo >&2 "failed"
+	if (cd "$base/$item"; . ./def; :) >&2; then
+		echo "ok $apply $item"
+	else
+		echo "err $apply $item"
 		exit=1
-	}
+	fi
 }
 
-[ -f "$host" ] || { echo>&2 "$host does not exist"; exit 1; }
+resolve() {
+	local item=${1:?}
+	shift
 
-while read item; do
 	case $item in
 	(module/*)
-		module "$item"
+		module "$item" "$@"
 		;;
-	(role/*)
-		while read role; do
-			module "$role"
+	(*/*)
+		while read item; do
+			resolve "$item" "$@"
 		done <$item
 		;;
+	(*)
+		die "unknown type: $item"
+		;;
 	esac
-done <$host
+}
 
+export apply=${1:?}
+export apply=${apply##*/}
+export base=$(cd $(dirname "$0")/..; pwd)
+export tmp=$(mktemp)
+export host=${host:-$(hostname -s)}
+export exit=0
+shift 1
+
+trap 'rm -rf "$tmp"' INT TERM EXIT HUP
+[ -x "$base/bin/do/$apply" ] || die "unknown script $base/bin/do/$apply"
+resolve "host/$host/modules" "$@"
 exit "$exit"
